create table Jobs (
	id INT,
	job_title VARCHAR(19),
	hourly_wage INT,
	date_created DATE,
	job_date DATE,
	job_active VARCHAR(50),
	positions INT,
	job_description TEXT,
	employer_id VARCHAR(8),
	location_lat DECIMAL(8,6),
	location_long DECIMAL(10,6)
);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (1, 'musician', 17, '2020/12/01', '2020/12/18', true, 1, 'neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit', 2, 49.625159, -122.481819);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (2, 'musician', 29, '2020/12/02', '2020/12/25', true, 2, 'purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam', 9, 49.901118, -122.898795);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (3, 'labourer', 26, '2020/12/02', '2020/12/28', true, 3, 'felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci', 4, 49.905339, -122.487845);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (4, 'handyman', 17, '2020/12/02', '2020/12/29', true, 2, 'vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio', 2, 49.380805, -122.174099);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (5, 'musician', 20, '2020/12/01', '2020/12/22', true, 1, 'morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend', 9, 49.061493, -122.93132);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (6, 'labourer', 16, '2020/12/01', '2020/12/23', true, 2, 'vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum', 1, 49.902369, -122.229978);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (7, 'cleaner', 25, '2020/12/01', '2020/12/27', true, 2, 'dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque', 9, 49.732648, -122.892285);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (8, 'labourer', 26, '2020/12/02', '2020/12/15', true, 1, 'id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst', 3, 49.168807, -122.240603);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (9, 'busser', 28, '2020/12/02', '2020/12/12', true, 1, 'nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere', 9, 49.948311, -122.482797);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (10, 'painter', 21, '2020/12/01', '2020/12/18', true, 2, 'sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat', 7, 49.401581, -122.240692);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (11, 'painter', 22, '2020/12/01', '2020/12/26', true, 1, 'maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet', 4, 49.533892, -122.921952);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (12, 'cleaner', 17, '2020/12/02', '2020/12/23', true, 3, 'justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit', 10, 49.312929, -122.412939);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (13, 'painter', 27, '2020/12/02', '2020/12/10', true, 1, 'quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet', 10, 49.450545, -122.997373);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (14, 'dishwasher', 15, '2020/12/02', '2020/12/10', true, 2, 'eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt', 10, 49.700439, -122.761876);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (15, 'landscaper', 21, '2020/12/01', '2020/12/23', true, 1, 'lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede', 8, 49.881317, -122.40298);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (16, 'agricultural worker', 19, '2020/12/02', '2020/12/30', true, 4, 'quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi', 9, 49.592851, -122.979745);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (17, 'agricultural worker', 26, '2020/12/02', '2020/12/15', true, 2, 'curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum', 2, 49.404504, -122.352727);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (18, 'musician', 16, '2020/12/02', '2020/12/28', true, 1, 'rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit', 3, 49.354887, -122.197187);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (19, 'cleaner', 30, '2020/12/01', '2020/12/11', true, 2, 'libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor', 4, 49.060239, -122.958202);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (20, 'agricultural worker', 24, '2020/12/01', '2020/12/13', true, 3, 'feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at', 6, 49.276808, -122.931294);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (21, 'labourer', 19, '2020/12/02', '2020/12/18', true, 3, 'magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur', 1, 49.763101, -122.487757);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (22, 'handyman', 18, '2020/12/02', '2020/12/08', true, 1, 'porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius', 6, 49.807743, -122.565902);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (23, 'agricultural worker', 19, '2020/12/02', '2020/12/29', true, 2, 'vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi', 9, 49.920694, -122.030159);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (24, 'musician', 30, '2020/12/01', '2020/12/18', true, 1, 'curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi', 5, 49.530753, -122.687906);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (25, 'landscaper', 18, '2020/12/02', '2020/12/23', true, 1, 'pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue', 5, 49.235599, -122.71148);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (26, 'landscaper', 23, '2020/12/02', '2020/12/27', true, 3, 'tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing', 10, 49.861453, -122.634492);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (27, 'labourer', 17, '2020/12/01', '2020/12/22', true, 3, 'tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus', 4, 49.331619, -122.087109);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (28, 'dishwasher', 15, '2020/12/02', '2020/12/24', true, 2, 'integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non', 5, 49.615263, -122.180647);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (29, 'dishwasher', 16, '2020/12/01', '2020/12/08', true, 1, 'ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et', 2, 49.088969, -122.735896);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (30, 'cleaner', 21, '2020/12/01', '2020/12/15', true, 3, 'odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus', 1, 49.334841, -122.148725);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (31, 'landscaper', 29, '2020/12/01', '2020/12/08', true, 4, 'vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a', 4, 49.725347, -122.102678);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (32, 'labourer', 28, '2020/12/01', '2020/12/08', true, 4, 'nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et', 1, 49.615236, -122.956874);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (33, 'handyman', 24, '2020/12/01', '2020/12/14', true, 1, 'diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla', 7, 49.960318, -122.357627);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (34, 'musician', 16, '2020/12/01', '2020/12/05', true, 3, 'congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor', 7, 49.06084, -122.578244);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (35, 'busser', 19, '2020/12/01', '2020/12/06', true, 2, 'dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi', 7, 49.640458, -122.771061);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (36, 'cleaner', 27, '2020/12/02', '2020/12/16', true, 1, 'vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula', 6, 49.698795, -122.752702);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (37, 'agricultural worker', 18, '2020/12/01', '2020/12/19', true, 1, 'odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae', 7, 49.215605, -122.631611);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (38, 'busser', 19, '2020/12/01', '2020/12/12', true, 1, 'consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam', 8, 49.21426, -122.423843);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (39, 'dishwasher', 25, '2020/12/01', '2020/12/16', true, 3, 'rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus', 9, 49.203224, -122.26657);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (40, 'landscaper', 21, '2020/12/02', '2020/12/07', true, 3, 'maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at', 2, 49.722554, -122.392861);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (41, 'agricultural worker', 21, '2020/12/02', '2020/12/22', true, 4, 'pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet', 8, 49.031557, -122.586179);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (42, 'dishwasher', 19, '2020/12/01', '2020/12/23', true, 1, 'vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla', 8, 49.69822, -122.480754);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (43, 'painter', 28, '2020/12/01', '2020/12/24', true, 1, 'felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie', 4, 49.733196, -122.295003);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (44, 'handyman', 15, '2020/12/01', '2020/12/07', true, 3, 'eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet', 8, 49.901199, -122.71074);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (45, 'cleaner', 18, '2020/12/02', '2020/12/21', true, 1, 'ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris', 9, 49.273219, -122.653477);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (46, 'agricultural worker', 24, '2020/12/02', '2020/12/18', true, 3, 'vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo', 3, 49.717694, -122.69986);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (47, 'painter', 25, '2020/12/01', '2020/12/15', true, 4, 'nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam', 7, 49.615172, -122.348468);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (48, 'landscaper', 28, '2020/12/01', '2020/12/15', true, 1, 'condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus', 10, 49.790467, -122.530037);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (49, 'dishwasher', 21, '2020/12/02', '2020/12/08', true, 2, 'eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit', 5, 49.847207, -122.193438);
insert into Jobs (id, job_title, hourly_wage, date_created, job_date, job_active, positions, job_description, employer_id, location_lat, location_long) values (50, 'handyman', 23, '2020/12/02', '2020/12/27', true, 2, 'porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi', 10, 49.818626, -122.138059);
