export const GET_FAVE_EMPLOYERS = 'GET_FAVE_EMPLOYERS';
export const GET_FAVE_WORKERS = 'GET_FAVE_WORKERS';
export const SEARCH_WORKERS = 'SEARCH_WORKERS';
export const SEARCH_JOBS = 'SEARCH_JOBS';
export const ADD_JOB = 'ADD_JOB';
export const CLEAR_JOBS = 'CLEAR_JOBS';
export const LOG_IN_WORKER = 'LOG_IN_WORKER';
export const LOG_IN_EMPLOYER = 'LOG_IN_EMPLOYER';
export const LOG_OUT = 'LOG_OUT';
export const ADD_APPLICATION = 'ADD_APPLICATION';
export const SET_APPLICATIONS = 'SET_APPLICATIONS';
export const GET_APPLICATIONS = 'GET_APPLICATIONS';


